spring:
  application:
    name: server

server:
  port: 19010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19010/eureka/  # Eureka 서버 URL
    register-with-eureka: false  # Eureka 서버에 등록
    fetch-registry: false  # Eureka 서버로부터 레지스트리 정보 가져오기
  instance:
    hostname: localhost  # 클라이언트 호스트 이름
